version: '3.9'
name: caddy

services:
  caddy:
    image: caddy:latest
    container_name: 'sysreptor-caddy'
    restart: unless-stopped
    command: caddy reverse-proxy --from https://192.168.0.85:443 --to http://127.0.0.1:8096
    volumes:
    - type: volume
      source: sysreptor-caddy-data
      target: /data
    network_mode: "host"

volumes:
  sysreptor-caddy-data:
    name: sysreptor-caddy-data